[package]
name = "better_todos"
version = "1.1.2"
edition = "2021"
author = "Harrison Hemstreet"
license = "MIT"
description = "This is a better todo that allows users to scaffold much faster. Write your todos and see them very clearly every time you compile."

[dependencies]
termcolor = "1.2.0"
